### ISSUE TITLE
Issues PM - June 2020

### ISSUE THREAD

**Issue by PM-OCEA** [ischerr/Scottish-Energy-Statistics-Hub#80]
Renewables and low carbon

- [x] Ren electricity generation - add in a chart and a table for an LA breakdown (from [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/834142/Renewable_electricity_by_local_authority_2014_to_2018.xlsx)).  The table should have a breakdown by technology for each LA.  This won't all add up to the Scottish total, so can you do an unallocated row which is the difference between the sum of the LAs and the Scottish total

- [x] Ren electricity capacity – capacity by LA breakdown.  We would need to do this the same way as the renewable generation by LA breakdown above

- [x] Ren elec capacity - add in an annual capacity by tech table which has the figures going back to 2000.  

- [x] RenHeat - three chart tabs - capacity, generation and no of installations.  In each we could have a drop down menu to select either technology or size to split the bars?

- [x] Renewable heat by tech type - remove the time series, as the totals don’t add up to overall capacity.  Instead include the 2018 and 2017 data from p26-27 of the renewable heat report (don’t include the %s in the tables).  Do a table with capacity, output and number of installations with a 2 year time series.  Incorporate the breakdown of energy from waste in table 7 as well.  Next update of this will be October 2020.

- [x] Renewable heat by size?  I think I asked for this to be included?  P24 of the renewable heat report – include capacity, output and number of installations (don’t worry about %s) by size category.  Include figures for 2018 and 2017 as per tech type.

- [x] LA breakdown of the overall ULEVs too

Local energy systems

- [x] COLO > output data table – add in generation output.  Make a chart of this too

Energy efficiency

- [x] Electricity consumption > by LA data table.  Add an extra column showing the total electricity consumption by LA, and make clear what’s there is average household electricity consumption.
Households and LA chart tabs not working?
LA data table – units should be kWh not GWh

- [x] Gas consumption > by LA data table.  Add an extra column showing the total electricity consumption by LA, and make clear what’s there is average household electricity consumption.  Have a title for the data table.  Include Shetland and Orkney in this table, even though their consumption is 0
LA data table – units should be kWh

- [x] Domestic EPCs – note on the charts and tables on the housing stock EPC and tenure tabs to say this is based on SAP 2012 RdSAP v9.93
Domestic EPCs, Housing tenure chart – rank from highest to lowest % at least band C
Domestic EPCs – add in an average EER rating chart (it’s in the ESD). 
Drop the SAP 2009 line in the chart here and the charts in the hub.  Keep the data in the data table.  

- [x] ECO measures > obligations chart - can the chart be changed to a pie chart, and drop total number of ECO measures 
ECO measures data table – flip so the dates read most recent to earliest.  Drop the total per 1000 households.  Update expected date and source link need updated. 

Consumers

- [x] LA energy bill – can you add extra versions of the map, one with average electricity bill and  one with average gas bill
Round the data here to the nearest pound
Electricity and gas cost breakdown tabs have broken

- [x] Dual fuel breakdown – drop the January – March 19 line.
Update expected is August 2020 and the source is  https://www.ofgem.gov.uk/publications-and-updates/default-tariff-cap-level-1-april-2020-30-september-2020

- [x] Switching data tables – flip so most recent is at the top

- [x] Restricted and prepayment meters – change title of tab to restricted meters
Include the Scotland total, and do a separate tab which has the time series with number rather than % of meters

System security

- [x] Maximum supply capacity – in the data table include a subtotal for Scottish capacity and imports.

Oil and gas

- [x] Coal production – I think the sheet we got from BEIS had data on employment in the coal sector.  Could you include?

**Comment by ischerr** [comment]
-  ~Can we link the chart with the data table, so that when you change the chart tab you also change the data table tab~

Home

- [x] Can we structure the boxes in a 3x3 formation?  By this I meant including the covid-19 box in the same shape as the rest within the 3x3 formation

Whole system

- [x] Energy balance > Energy flow data table: could you add the figures in as well as the %s?  Double check the %s here – they don’t match with what I have here

- [x] Energy economy > chart and data table – include a total exports 
Chart for turnover / GVA – latest data is 2017, chart subtitle says 2018 

Renewables and low carbon

- [x] Electricity generation > data tables – move pumped hydro and other after fossil fuels in the table.  Can you italicise the headings for renewables, low carbon and fossil fuels
Animation chart doesn’t seem to be working?
Double check the figures for 2004 and 2005, they don't seem to be pulling through correctly (oil for 2004 in particular looks wrong)
Add a separate data table for Scotland only with renewables, % renewables, nuclear, % nuclear, low carbon, % low carbon, fossil fuels, % fossil fuels
include the 2004-08 data in the first chart

- [x] Renewable electricity generation > Scottish proportion data table – rename the title to Scottish proportion of UK total
Wind and hydro titles – change to Scottish generation compared to European countries (GWh).  UK should be rest of UK in this table

- [x] Ren elec generation - remove the 2010 Q4 row in the data table

- [x] Ren elec Sources - add into the table headers the date which the data refers

- [x] Renewable electricity pipeline – include the excel planning table data extract into the hub.  Can you include the number of turbines into it?  I think this means that we can discontinue the webpage as everything would be incorporated into the hub

- [x] Renewable electricity sources > summary data table – change title to wind summary

- [x] Grid emissions - on the interactive and static charts, can you include a line to denote the 50 gCO2e/kWh ambition for 2020

- [x] Renewable heat target – title of chart should be ‘share of renewable heat of non-electrical heat demand’

- [x] Dom RHI - the urban/rural on/off grid table - the dates are wrong for this - the domestic scheme runs from April 2014 not Nov 2011.  Could you add a stacked bar chart of % on/off grid for each technology and the total?

- [x] Dom RHI & non-dom RHI - update the heat generated table with the May 2020 data I sent you

- [x] Non-dom RHI - Could you add a stacked bar chart of % on/off grid for each technology and the total?

- [x] Domestic and non-dom RHI - in what BEIS publish there are hidden tables, S1.2b and S2.5b which breakdown number of accreditations by urban/rural and off/on gas grid by technology.  Bring through as separate tables in the hub, with the columns as urban on-grid, urban off-grid, rural on-grid, rural off-grid, total urban, total rural, total on-grid, total off-grid, total.

- [x] Transport – flip ULEVs and biofuels around

- [x] ULEVs - link in the Transport Scotland stats as a source for this page: https://www.transport.gov.scot/publication/scottish-transport-statistics-no-38-2019-edition/chapter-13-environment-and-emissions/
The units for the charge provided should be MWh

- [x] Domestic RHI - Chart has GWh as the label, remove as it should be number installations
Table 2.4 in the data BEIS publishes has a breakdown of accredited installations by LA - can we add into the data tables for dom RHI?

Local energy systems

- [x] COLO – Can you set the chart so that it takes the month and year rather than just the year on the x-axis?  The next data for this will be out in March 2021 and will be based on Dec 2020 data

Energy efficiency

- [x] Energy consumption > by LA – something weird has happened with the Shetland and Orkney consumption

- [x] Heat consumption > sector data table - include total 

- [x] Household energy intensity – put emissions intensity figure in the data table to 2 dp

- [x] Transport consumption – title and units for the data table.  Italicise personal and freight to make clear they’re subtotals

- [x] Loft insulation > thickness table - Update figures to the 1 dp figures in the email I forwarded from Claire Wood – column headings should be 300mm or more, 200-299mm, 100-199mm, 1-99mm, None, 200mm or better.  200mm or better should be the figure to the right of each bar in the chart

Consumers

- [x] Split the tabs into the following sections:
**Bills:** Energy Bill Payment Methods, Electricity Bill Prices, Gas Bill Prices, LA energy bill, Dual Fuel Bill Breakdown, Fixed Tariffs
**Vulnerability:** Fuel Poverty, Vulnerability
**Consumer choice:** Primary Heating Fuel, Households not on the Gas Grid, Energy Supplier Switching, Market Structure, Energy Customers on Non-home Supplier
**Meters:** Smart Meters, Restricted meters

- [x] Electricity bill prices and gas bill prices > regional breakdown chart – put total at the top, then in order the payment types from highest to lowest 

- [x] Vulnerability data tables – flip so most recent is at the top

- [x] Market structure – we can say this is Scotland as all suppliers that operate in GB technically have to supply anywhere

- [x] Home supplier > data tables – reorder to elec time series, elec payment methods, gas time series, gas payment methods

- [x] Smart meters – add % to the interactive chart

System security

- [x] Rename system security to electricity and gas systems

- [x] Rename maximum supply capacity… to electricity system security

- [x] Move off gas grid tab from consumers to just before gas security

- [x] Gas security – change tab title to UK proportion.  Typo of proportion in the title of the data table

Oil and gas

- [x] Primary energy – oil and gas > data tables, stop it from running into 2 pages

- [x] Oil and gas GVA – Change chart title to Gross value added (GVA) associated with oil and gas production
